# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  targets:
    description: Comma separated list of external scrape targets, e.g., "192.168.5.2:7000,192.168.5.3:7000"; do not add the protocol!
    type: string
  labels:
    description: Comma separated list of label:value pairs.
    type: string
  job_name:
    description: Name of external scrape configuration jobs.
    type: string
    default: "external_jobs"
  metrics_path:
    description: Metrics path for external jobs.
    type: string
  scheme:
    description: dfdf
    type: string
  basic_auth:
    # TODO: this should be removed after juju secrets are available
    description: username:password
    type: string
  tls_config_ca_file:
    # TODO: this should be removed after juju secrets are available
    description: dfdf
    type: string
