# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  targets:
    description: Comma separated list of external scrape targets.
    type: string
  labels:
    description: Comma separted list of label:value pairs.
    type: string
  job-name:
    description: Name of external scrape configuration jobs.
    type: string
    default: "external_jobs"
  metrics-path:
    description: Metrics path for external jobs.
    type: string
